### ISSUE TITLE
Bug: code.google.com/p/rsc/qr no longer valid

### ISSUE THREAD

**Issue by bcorcoran** [balasanjay/totp#1]
As the title suggests, code.google.com/p/rsc/qr is no longer valid. When using this project, one now receives the following error:

`imports code.google.com/p/rsc/qr: unable to detect version control system for code.google.com/ path`

It is due to the fact that code.google.com is officially archived. I am requesting that you export rsc's repo to github and reference that instead.

**Comment by balasanjay** [comment]
I'm away from my usual computer at the moment, so I wrote this in the Github editor UI.

If you can verify it works, I'll go ahead and merge it now. Otherwise, I'll merge shortly, once I can try compiling this.

**Comment by bcorcoran** [comment]
Unfortunately it doesn't, because the automatically migrated code references code.google.com again in qr.go: 

https://github.com/rsc/rsc/blob/master/qr/qr.go

I updated all the necessary references and submitted PR's for them in rsc's repo.

**Comment by shalecraig** [comment]
Looks like this PR is blocked on https://github.com/rsc/rsc/issues/4

**Comment by zaphar** [comment]
It looks like Russ isn't particularly interested in his qr lib being used by folks. If there is interest I can look into using a different QR code library and putting together a pull request for it. There are a fair number of them out there. Just need to select one.

**Comment by balasanjay** [comment]
Sure, I'd be happy to accept a PR for this. Otherwise, I'll try to look
into this shortly.

If you need to test with the Google Authenticator app, checkout TestPrint
https://github.com/balasanjay/totp/blob/master/totp_test.go#L14.

**Comment by zaphar** [comment]
Pull request sent: https://github.com/balasanjay/totp/pull/3
